### PR TITLE
Spotify uses spaces instead of commas to separate scope

### PR DESCRIPTION
**Pull request by sbarre**

### CODE REVIEW

**Comment by sbarre** [comment]
Not sure why this is failing, I literally just copied from the Laravel code and pasted into the Provider and changed the value in the variable.

**Comment by ghost** [comment]
There is a space to much between the curly brace and the variable comment and have you tested the provider with the spaces as seperator?

When I created the Provider I tested it with the default, which are commas, and it worked just fine.

**Comment by sbarre** [comment]
Fixed code style issue, removed extraneous blank line

**Comment by sbarre** [comment]
I did in fact test it, and it failed, so I looked up the Spotify API docs, patched my local code, and then it worked. 

And that's why I went to the trouble of forking the repo and submitting this pull request. :) 

If you look at the API docs here:

https://developer.spotify.com/web-api/using-scopes/

You see the scopes are space-separated in their provided example as well.

**Comment by ghost** [comment]
Alright, thanks for pull request. Merged it and tagged v1.0.7.

**Pull request merged**
